<br>
<div class="col-md-12">
    <h2>New word:</h2>

    <br>
    <br>

    <form action="" method="post">
        <div class="col-md-6">
            <div class="form-group">
                <label for="word">Word</label>
                <input name="word" type="text" class="form-control" id="word" placeholder="Enter word" required>
            </div>
        </div>


        <div class="clearfix"></div>
        <div class="col-md-12">
            <br>
            <input type="submit" class="btn btn-primary" value="Add">
        </div>
    </form>
</div>