<br>
<br>

<div class="col-md-12">

    <h1 style="font-family: Nakula">Pattern table</h1>
    <br>
    <div class="search-box">
        <input type="text" autocomplete="off" placeholder="Search id..."/>
        <br>
        <br>
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th></th>
                <th>Id</th>
                <th>Pattern</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <div class="result">
            </div>
            <?php foreach ($arr as $element) { ?>
                <tr>

                    <td></td>
                    <td><?php echo $element['id'] ?></td>
                    <td><?php echo $element['pattern'] ?></td>
                    <td><a href="Pattern?id=<?php echo $element['id'] ?>" class="btn btn-warning">Edit</a>
                    </td>
                    <td>
                        <form method="post">
                            <input type="hidden" name="id" value="<?php echo $element['id'] ?>">
                            <input type="submit" class="btn btn-danger" value="Delete" name="delete">
                        </form>
                    </td>

                </tr>
            <?php } ?>


        </table>
    </div>
<div style="display: flex;justify-content: space-around ">
    <ul class="pagination" >
        <li class="page-link" style="margin-right: 25px"><a style="color: black;" href="?pageno=1">First</a></li>
        <li style="margin-right: 25px" class="<?php if ($pageno <= 1) {
            echo 'disabled';
        } ?>">
            <a class="page-link" style="color: black;" href="<?php if ($pageno <= 1) {
                echo '#';
            } else {
                echo "?pageno=" . ($pageno - 1);
            } ?>">Prev</a>
        </li>
        <li style="margin-right: 25px" class="<?php if ($pageno >= $total_pages) {
            echo 'disabled';
        } ?>">
            <a class="page-link" style="color: black;" href="<?php if ($pageno >= $total_pages) {
                echo '#';
            } else {
                echo "?pageno=" . ($pageno + 1);
            } ?>">Next</a>
        </li>
        <li class="page-link" style="margin-right: 5px"><a style="color: black;" href="?pageno=<?php echo $total_pages; ?>">Last</a></li>
    </ul>
</div>
</div>
